name: Main Branch Build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
      - name: Lint
        run: gofmt -d .
      - name: Build Functions
        run: make build
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --verbose --stage dev --region us-east-2
      - name: Integration Tests
        run:  go test -v ./test/
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --verbose --stage prod --region us-east-2
