name: Main Branch Build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v2
      - name: Install SLS
        run: sudo npm install -g sls
      - name: Deploy Dev Env
        run: make deploy-dev
      - name: Run Integration Tests
        run: go test ./test/ -v
      - name: Deploy Prod Env
        run: make deploy